# Generated by Django 3.2.25 on 2024-12-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20241209_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geo',
            name='lat',
            field=models.DecimalField(decimal_places=12, max_digits=12),
        ),
        migrations.AlterField(
            model_name='geo',
            name='lng',
            field=models.DecimalField(decimal_places=12, max_digits=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
