# Generated by Django 3.2.25 on 2024-12-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20241209_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geo',
            name='lat',
            field=models.DecimalField(decimal_places=9, max_digits=12),
        ),
        migrations.AlterField(
            model_name='geo',
            name='lng',
            field=models.DecimalField(decimal_places=9, max_digits=12),
        ),
    ]
