# Generated by Django 3.2.25 on 2024-12-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_album_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='thumbnailUrl',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.URLField(),
        ),
    ]
