# Generated by Django 3.2.25 on 2024-12-10 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_post_comment_postid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='album',
            new_name='albumId',
        ),
    ]
